# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
<<<<<<< HEAD
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
=======

>>>>>>> new-theme
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
<<<<<<< HEAD

title: Aerodynamics of an F1 car
email: h1710095@nushigh.edu.sg
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! This is a website discussing everything about the Formula One aerodynamics. This is for a PC5132 Module Project.
baseurl: "/pc5132-site" # the subpath of your site, e.g. /blog
url: "http://kimame04.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Kimame04

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
title: Aerodynamics of an F1 Car
tagline: A site showing the usage of Jekyll custom theme
email: h1710095@nushigh.edu.sg
description: >- # this means to ignore newlines until "baseurl:"
  This website was created as a demonstration for Jekyll custom theme
  named minimal-categorized. Its main feature is to aggregate posts into
  categories, witch are easily distinguishable
baseurl: "/pc5132-site" # the subpath of your site, e.g. /blog
url: "https://kimame04.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: vrky
twitter:
  username: Kimame04
  card: summary
plugins:
  - jekyll-seo-tag

# Build settings
remote_theme: ItsMeaga1n/minimal-categorized
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
>>>>>>> new-theme
